version: "3.8"

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - red-cluster
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  migrate:
    image: gerardoherr/django-app:latest
    depends_on:
      - db
    command: python manage.py migrate
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=db
      - DB_USER=user
      - DB_PASSWORD=pass
    networks:
      - red-cluster
    deploy:
      restart_policy:
        condition: on-failure

  web:
    image: gerardoherr/django-app:latest
    depends_on:
      - db
      - migrate
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=db
      - DB_USER=user
      - DB_PASSWORD=pass
    networks:
      - red-cluster
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  red-cluster:
    driver: overlay
    attachable: true

volumes:
  postgres_data: